spring:
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
datastore:
  datasource:
    url: 'jdbc:h2:file:./target/database/h2'
    username: 'sa'
    password:
    driver-class-name: org.h2.Driver
    hibernate-dialect: org.hibernate.dialect.H2Dialect
  basic-auth-users:
    test-user: test-password!
    other-test-user: other-test-password!
